### ISSUE TITLE
Error in library(quitte) : there is no package called ‘quitte’

### ISSUE THREAD

**Issue by zztatjana** [aodenweller/green-h2-upscaling#1]
If I follow your instructions (Reproduction mode (default)) in the README.md file and want to run the main.Rmd, then I got the following error for the library(quitte): Error in library(quitte) : there is no package called ‘quitte’.

Since there is no package provided by R and I also haven't found one in your provided files, I am wondering if this is the right library after all? 
I also looked it up online and I didn't find something or something similar to the library(quitte). If I commend out the library I will get a new error in the step of the IEA Hydrogen Projects Database: Error in revalue.levels(., status = c(Decommisioned = "Decommissioned")) : could not find function "revalue.levels". But I am not sure if this error is connected to the library which does not exist.

For that reason, I wanted to inquire if you would know a possible alternative to how this error could be fixed?

Kind regards and thank you for sharing this very interesting approach!

**Comment by aodenweller** [comment]
Hi there,
Thanks for your interest and sorry for the confusion. You can find the quitte package here: https://github.com/pik-piam/quitte
Best wishes,
Adrian
